### ISSUE TITLE
the other way to refresh icon

### ISSUE THREAD

**Issue by ajenpan** [elmoiv/PopCat.exe#1]
hi, there.
if modify the `popCatClosed.ico` to `popCatClosed.dll` and `popCatOpen.ico` to `popCatOpen.dll`
so that don't need to set the Regedit for refresh icon

**Comment by elmoiv** [comment]
Thank you for contributing. Credited you btw.

> # Requirements
> You need to download the following files:
> - [Pop Cat Closed DLL](https://github.com/elmoiv/PopCat.exe/blob/main/requirements/popCatClosed.dll?raw=true)
> - [Pop Cat Open DLL](https://github.com/elmoiv/PopCat.exe/blob/main/requirements/popCatOpen.dll?raw=true)
> - [Pop Cat Sound](https://github.com/elmoiv/PopCat.exe/blob/main/requirements/popCatSound.wav?raw=true)
> 
> *Thanks to [ajenpan](https://github.com/ajenpan): Pop Cat icons extensions are renamed to .dll to enable auto refresh without editing registery*
